//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        public int Id { get; set; }
        [DisplayName("帳號")]
        [Required(ErrorMessage ="帳號不可空白")]
        public string Mem_id { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        public string Mem_password { get; set; }
        [DisplayName("名稱")]
        [Required(ErrorMessage = "名稱不可空白")]
        public string Name { get; set; }
        [DisplayName("電話")]
        [Required(ErrorMessage = "電話不可空白")]
        [StringLength(10,ErrorMessage ="電話號碼為10位",MinimumLength =10)]
        public string Phone { get; set; }
    }
}
