//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Product
    {
        public int Id { get; set; }

        [DisplayName("產品名稱")]
        public string ProductName { get; set; }
        [DisplayName("金額")]
        public int ProductMoney { get; set; }
        [DisplayName("介紹")]
        public string ProductIntrodution { get; set; }
        public string PId { get; set; }
        public string ImageName { get; set; }
    }
}
